version: "0.2"
ignorePaths: ["README.md", "troubleshooting-moip.md"]
files: ["*.md"]
dictionaryDefinitions: []
dictionaries: []
words: [
  "AMWA",
  "arping",
  "Bootable",
  "CBNT",
  "Clonezilla",
  "comptia",
  "DCIM",
  "DECSAR",
  "dhclient",
  "dhcpcd",
  "EXFO",
  "flushdns",
  "IPAM",
  "Iperf",
  "kenlon",
  "kozk",
  "Kurose",
  "Liebman",
  "Meinberg",
  "Memtest",
  "mydnsserver",
  "netsh",
  "netshoot",
  "networkctl",
  "Nmap",
  "NMOS",
  "noall",
  "nocmd",
  "nslookup",
  "ntpq",
  "OTDR",
  "OTDRs",
  "pathping",
  "pcap",
  "pinout",
  "reflectometer",
  "reflectometers",
  "Rescatux",
  "rrtype",
  "sdpoker",
  "SirusXM",
  "SMPTE",
  "tcpdump",
  "traceroute",
  "tracert",
  "traefik",
  "Ventoy",
  "Wireshark"
]
ignoreWords: []
import: []
