name: Build Slides

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: 3.1.11
      - run: |
          pandoc --citeproc \
            --filter=node_modules/.bin/mermaid-filter \
            --from=markdown+yaml_metadata_block+emoji \
            --slide-level=3 \
            ./troubleshooting-moip.md \
            -o ./troubleshooting-moip.pptx
      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: michaelliebman
      - uses: actions/upload-artifact@v4
        with:
          name: troubleshooting-moip_${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}.pptx
          path: troubleshooting-moip.pptx
